### ISSUE TITLE
Consider Self-Reminder Functionality

### ISSUE THREAD

**Issue by Khitiara** [robotbrain/rubybot#3]
Should natural-ish language be used (makes parsing harder) or a stricter command? Should they be persisted?

**Comment by RX14** [comment]
for a command `tell`, I think:
- can be called by `.tell ...`
- can be called by `ElrosGem, tell ...`

**Comment by Khitiara** [comment]
idk about the first one
I was thinking `?remindme <at <iso8601 time|<tod> on <iso860 date>>|in <num> <units>> <to|that> <phrase>`

**Comment by Khitiara** [comment]
Updated issue to clarify
