### ISSUE TITLE
Investigate issues from 02JanDal

### ISSUE THREAD

**Issue by Khitiara** [robotbrain/rubybot#5]
WTTS

**Comment by Khitiara** [comment]
Done

**Comment by Khitiara** [comment]
Boing?

**Comment by RX14** [comment]
so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?so doesithandlereallylongcomentswell?

**EDIT:** It does!

**Comment by RX14** [comment]
vim lodhjsahdjksahdjkasl
